# Generated by Django 4.2.4 on 2023-09-01 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("names", models.CharField(max_length=150, verbose_name="Nombres")),
                (
                    "cedula",
                    models.CharField(max_length=8, unique=True, verbose_name="Cedula"),
                ),
                (
                    "date_joined",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="Fecha de registro"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now=True)),
                ("date_update", models.DateTimeField(auto_now_add=True)),
                ("edad", models.PositiveIntegerField(default=0, max_length=2)),
                (
                    "salario",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("state", models.BooleanField(default=True)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos/%Y/%m/%D"
                    ),
                ),
                (
                    "cv",
                    models.ImageField(blank=True, null=True, upload_to="CVs/%Y/%m/%D"),
                ),
            ],
            options={
                "verbose_name": " empleado",
                "verbose_name_plural": "empleados",
                "db_table": "empleados",
                "ordering": ["id"],
            },
        ),
    ]
