# Generated by Django 4.2.4 on 2023-09-01 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coreBlog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("names", models.CharField(max_length=100, verbose_name="nombre")),
            ],
            options={
                "verbose_name": "tipo",
                "verbose_name_plural": "tipos",
                "ordering": ["id"],
            },
        ),
        migrations.AlterModelTable(
            name="empleado",
            table=None,
        ),
        migrations.AddField(
            model_name="empleado",
            name="type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="coreBlog.type",
            ),
            preserve_default=False,
        ),
    ]
