# Generated by Django 4.2.4 on 2023-10-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coreBlog", "0002_userprofile_descripcion_userprofile_edad_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["id"],
                "verbose_name": "usuario",
                "verbose_name_plural": "usuarios",
            },
        ),
    ]
