# Generated by Django 4.2.4 on 2023-10-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreBlog", "0004_post_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="fotos_post/%Y/%m/%D",
                verbose_name="Foto",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="fotos_post/%Y/%m/%D",
                verbose_name="Foto",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(max_length=500),
        ),
    ]
