# Generated by Django 4.2.4 on 2023-10-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coreBlog", "0005_comment_image_post_image_alter_comment_text_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="image",
            new_name="image_post",
        ),
    ]
